// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test1() {
    driver.get("http://localhost:8080/demo/library.html");
    driver.manage().window().setSize(new Dimension(1464, 666));
    driver.findElement(By.cssSelector(".button-form:nth-child(4) > input")).click();
    driver.findElement(By.linkText("Return")).click();
    driver.findElement(By.id("register_book")).click();
    driver.findElement(By.id("register_book")).sendKeys("some book");
    driver.findElement(By.id("register_book_submit")).click();
    driver.findElement(By.linkText("Return")).click();
    driver.findElement(By.id("register_borrower")).click();
    driver.findElement(By.id("register_borrower")).sendKeys("some borrower");
    driver.findElement(By.id("register_borrower_submit")).click();
    driver.findElement(By.linkText("Return")).click();
    driver.findElement(By.id("lend_book")).click();
    driver.findElement(By.id("lend_book")).sendKeys("some book");
    driver.findElement(By.id("lend_borrower")).sendKeys("some borrower");
    driver.findElement(By.id("lend_book_submit")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("SUCCESS"));
  }
}
