version: '3'

services:

  jenkins:
    user: root
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOME}/dev:/home"

volumes:
  jenkins-data:

