# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://localhost:8080/demo/library.html")
    self.driver.set_window_size(1464, 666)
    self.driver.find_element(By.CSS_SELECTOR, ".button-form:nth-child(4) > input").click()
    self.driver.find_element(By.LINK_TEXT, "Return").click()
    self.driver.find_element(By.ID, "register_book").click()
    self.driver.find_element(By.ID, "register_book").send_keys("some book")
    self.driver.find_element(By.ID, "register_book_submit").click()
    self.driver.find_element(By.LINK_TEXT, "Return").click()
    self.driver.find_element(By.ID, "register_borrower").click()
    self.driver.find_element(By.ID, "register_borrower").send_keys("some borrower")
    self.driver.find_element(By.ID, "register_borrower_submit").click()
    self.driver.find_element(By.LINK_TEXT, "Return").click()
    self.driver.find_element(By.ID, "lend_book").click()
    self.driver.find_element(By.ID, "lend_book").send_keys("some book")
    self.driver.find_element(By.ID, "lend_borrower").send_keys("some borrower")
    self.driver.find_element(By.ID, "lend_book_submit").click()
    assert self.driver.find_element(By.ID, "result").text == "SUCCESS"
  
