;             
CREATE USER IF NOT EXISTS "" SALT '' HASH '' ADMIN;           
CREATE SCHEMA IF NOT EXISTS "ADMINISTRATIVE" AUTHORIZATION "";
CREATE SCHEMA IF NOT EXISTS "AUTH" AUTHORIZATION "";          
CREATE SCHEMA IF NOT EXISTS "LIBRARY" AUTHORIZATION "";       
CREATE SEQUENCE "AUTH"."SYSTEM_SEQUENCE_6608652E_F4BC_46BC_A456_0FCA964E591D" START WITH 1 BELONGS_TO_TABLE;  
CREATE SEQUENCE "LIBRARY"."SYSTEM_SEQUENCE_A08E4C08_164A_4348_9A78_C229789BAEF3" START WITH 4 BELONGS_TO_TABLE;               
CREATE SEQUENCE "LIBRARY"."SYSTEM_SEQUENCE_A416DDFE_1291_4BF1_B8C0_7F3A8EC53F92" START WITH 4 BELONGS_TO_TABLE;               
CREATE SEQUENCE "LIBRARY"."SYSTEM_SEQUENCE_C4EA4E4C_FC2D_4DF9_9937_3D93A483B1EE" START WITH 1 BELONGS_TO_TABLE;               
CREATE CACHED TABLE "ADMINISTRATIVE"."flyway_schema_history"(
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL
);     
ALTER TABLE "ADMINISTRATIVE"."flyway_schema_history" ADD CONSTRAINT "ADMINISTRATIVE"."flyway_schema_history_pk" PRIMARY KEY("installed_rank");
-- 4 +/- SELECT COUNT(*) FROM ADMINISTRATIVE.flyway_schema_history;           
INSERT INTO "ADMINISTRATIVE"."flyway_schema_history" VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, '', TIMESTAMP '2020-04-14 22:19:07.888525', 0, TRUE),
(0, NULL, '<< Flyway Schema Creation >>', 'SCHEMA', '"ADMINISTRATIVE","LIBRARY","AUTH"', NULL, '', TIMESTAMP '2020-04-14 22:19:07.888525', 0, TRUE),
(1, '1', 'Create person table', 'SQL', 'V1__Create_person_table.sql', 2000967190, '', TIMESTAMP '2020-04-14 22:19:07.919772', 2, TRUE),
(2, '2', 'Rest of tables for auth and library', 'SQL', 'V2__Rest_of_tables_for_auth_and_library.sql', 1047360475, '', TIMESTAMP '2020-04-14 22:19:07.95102', 6, TRUE);          
CREATE INDEX "ADMINISTRATIVE"."flyway_schema_history_s_idx" ON "ADMINISTRATIVE"."flyway_schema_history"("success");           
CREATE CACHED TABLE "LIBRARY"."BORROWER"(
    "ID" INT DEFAULT (NEXT VALUE FOR "LIBRARY"."SYSTEM_SEQUENCE_A08E4C08_164A_4348_9A78_C229789BAEF3") NOT NULL NULL_TO_DEFAULT SEQUENCE "LIBRARY"."SYSTEM_SEQUENCE_A08E4C08_164A_4348_9A78_C229789BAEF3",
    "NAME" VARCHAR(100) NOT NULL
);   
ALTER TABLE "LIBRARY"."BORROWER" ADD CONSTRAINT "LIBRARY"."CONSTRAINT_A" PRIMARY KEY("ID");   
-- 3 +/- SELECT COUNT(*) FROM LIBRARY.BORROWER;               
INSERT INTO "LIBRARY"."BORROWER" VALUES
(1, 'alice'),
(2, 'bob'),
(3, 'carol');            
CREATE CACHED TABLE "LIBRARY"."BOOK"(
    "ID" INT DEFAULT (NEXT VALUE FOR "LIBRARY"."SYSTEM_SEQUENCE_A416DDFE_1291_4BF1_B8C0_7F3A8EC53F92") NOT NULL NULL_TO_DEFAULT SEQUENCE "LIBRARY"."SYSTEM_SEQUENCE_A416DDFE_1291_4BF1_B8C0_7F3A8EC53F92",
    "TITLE" VARCHAR(100) NOT NULL
);      
ALTER TABLE "LIBRARY"."BOOK" ADD CONSTRAINT "LIBRARY"."CONSTRAINT_1" PRIMARY KEY("ID");       
-- 3 +/- SELECT COUNT(*) FROM LIBRARY.BOOK;   
INSERT INTO "LIBRARY"."BOOK" VALUES
(1, 'a'),
(2, 'b'),
(3, 'c');          
CREATE CACHED TABLE "LIBRARY"."LOAN"(
    "ID" INT DEFAULT (NEXT VALUE FOR "LIBRARY"."SYSTEM_SEQUENCE_C4EA4E4C_FC2D_4DF9_9937_3D93A483B1EE") NOT NULL NULL_TO_DEFAULT SEQUENCE "LIBRARY"."SYSTEM_SEQUENCE_C4EA4E4C_FC2D_4DF9_9937_3D93A483B1EE",
    "BOOK" INT NOT NULL,
    "BORROWER" INT NOT NULL,
    "BORROW_DATE" DATE NOT NULL
);
ALTER TABLE "LIBRARY"."LOAN" ADD CONSTRAINT "LIBRARY"."CONSTRAINT_2" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM LIBRARY.LOAN;   
CREATE CACHED TABLE "AUTH"."USER"(
    "ID" INT DEFAULT (NEXT VALUE FOR "AUTH"."SYSTEM_SEQUENCE_6608652E_F4BC_46BC_A456_0FCA964E591D") NOT NULL NULL_TO_DEFAULT SEQUENCE "AUTH"."SYSTEM_SEQUENCE_6608652E_F4BC_46BC_A456_0FCA964E591D",
    "NAME" VARCHAR(100) NOT NULL,
    "PASSWORD_HASH" VARCHAR(100)
);             
ALTER TABLE "AUTH"."USER" ADD CONSTRAINT "AUTH"."CONSTRAINT_2" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM AUTH.USER;      
ALTER TABLE "LIBRARY"."LOAN" ADD CONSTRAINT "LIBRARY"."CONSTRAINT_23B" FOREIGN KEY("BORROWER") REFERENCES "LIBRARY"."BORROWER"("ID") ON DELETE CASCADE NOCHECK;               
ALTER TABLE "LIBRARY"."LOAN" ADD CONSTRAINT "LIBRARY"."CONSTRAINT_23" FOREIGN KEY("BOOK") REFERENCES "LIBRARY"."BOOK"("ID") ON DELETE CASCADE NOCHECK;        
