// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Test1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void test1() {
    driver.Navigate().GoToUrl("http://localhost:8080/demo/library.html");
    driver.Manage().Window.Size = new System.Drawing.Size(1464, 666);
    driver.FindElement(By.CssSelector(".button-form:nth-child(4) > input")).Click();
    driver.FindElement(By.LinkText("Return")).Click();
    driver.FindElement(By.Id("register_book")).Click();
    driver.FindElement(By.Id("register_book")).SendKeys("some book");
    driver.FindElement(By.Id("register_book_submit")).Click();
    driver.FindElement(By.LinkText("Return")).Click();
    driver.FindElement(By.Id("register_borrower")).Click();
    driver.FindElement(By.Id("register_borrower")).SendKeys("some borrower");
    driver.FindElement(By.Id("register_borrower_submit")).Click();
    driver.FindElement(By.LinkText("Return")).Click();
    driver.FindElement(By.Id("lend_book")).Click();
    driver.FindElement(By.Id("lend_book")).SendKeys("some book");
    driver.FindElement(By.Id("lend_borrower")).SendKeys("some borrower");
    driver.FindElement(By.Id("lend_book_submit")).Click();
    Assert.That(driver.FindElement(By.Id("result")).Text, Is.EqualTo("SUCCESS"));
  }
}
