pipeline {

  agent {
    node {
      label 'master'
    }
  }

  stages {

    stage('Build') {
      steps {
        sh 'gradle clean assemble'
      }
    }

    stage('Test') {
      steps {
        sh 'gradle cucumber'
        sh 'gradle test'
      }
      post {
        always {
          junit 'build/test-results/test/*.xml'
        }
      }
    }

  }

}
